#!/usr/bin/env python3
"""build_control_set.py — Case_02 (port Fase 5).

Generates 02_CASES/Case_02_SecureBorder_Solutions/02_PHASE2_RULES_RICH/control_set.yaml
from the Control Set tables in Doc18_Rules_Catalog.md (single source of truth).

Fixes the Case_01 defect where status fields were parsed as the literal
string '**' (split-at-first-colon on bold markers): statuses here are read
positionally from the catalog table cells and validated against the posture
enum.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DOC18 = ROOT.parent / "Doc18_Rules_Catalog.md"
OUT = ROOT / "control_set.yaml"

STATUSES = {"IMPLEMENTED", "PARTIAL", "NOT IMPLEMENTED", "N/A", "—", "N/A (non-AI scope)"}


def parse_row(ln):
    cells = [c.strip() for c in ln.split("|")[1:-1]]
    if not cells:
        return None
    rid = cells[0]
    if re.match(r"^CR-D-\d\d\.\d-\d{3}$", rid):
        if len(cells) == 19:   # standard CR table (17 + F23/F24)
            return dict(id=rid, description=cells[1], sources=cells[2], sub_domain=cells[3],
                        ni=cells[4], priority=cells[5], verification=cells[6], impl=cells[7],
                        related_goals=cells[8], dependencies=cells[9], type_line=cells[10],
                        csf=cells[11], pf=cells[12], airmf=cells[13],
                        status_csf=cells[14], status_privacy=cells[15], status_airmf=cells[16],
                        traceability=cells[17], frameworks_ref=cells[18], kind="CR")
        if len(cells) == 20:   # CR tables with Case_02-specific column
            return dict(id=rid, description=cells[1], sources=cells[2], sub_domain=cells[3],
                        ni=cells[4], priority=cells[5], verification=cells[6], impl=cells[7],
                        related_goals=cells[8], dependencies=cells[9], case02_specific=cells[10],
                        type_line=cells[11], csf=cells[12], pf=cells[13], airmf=cells[14],
                        status_csf=cells[15], status_privacy=cells[16], status_airmf=cells[17],
                        traceability=cells[18], frameworks_ref=cells[19], kind="CR")
    if re.match(r"^BPR-D-\d\d\.\d-\d{3}$", rid):
        if len(cells) == 16:   # BPR table (14 + F23/F24)
            return dict(id=rid, description=cells[1], sources=cells[2], sub_domain=cells[3],
                        priority=cells[4], verification=cells[5], related_crs=cells[6],
                        type_line=cells[7], csf=cells[8], pf=cells[9], airmf=cells[10],
                        status_csf=cells[11], status_privacy=cells[12], status_airmf=cells[13],
                        traceability=cells[14], frameworks_ref=cells[15], kind="BPR")
    return None


def main():
    section = None
    controls, problems = [], []
    for ln in DOC18.read_text(encoding="utf-8").split("\n"):
        if ln.startswith("## 4. COMPLIANCE"):
            section = "CR"
        elif ln.startswith("## 5. BEST PRACTICE") or ln.startswith("## 9. EXPANDED"):
            section = "BPR"
        elif re.match(r"^## 6\.|^## 7\.|^## 8", ln):
            section = None
        if section not in ("CR", "BPR"):
            continue
        c = parse_row(ln)
        if not c:
            continue
        # the Case_01 '**' parsing bug is structurally impossible here; assert anyway
        for k in ("status_csf", "status_privacy", "status_airmf"):
            if not (c[k].startswith(("N/A", "—", "IMPLEMENTED", "PARTIAL", "NOT IMPLEMENTED"))):
                problems.append(f"{c['id']}: bad {k}={c[k]!r}")
        controls.append(c)

    cr = [c for c in controls if c["kind"] == "CR"]
    bpr = [c for c in controls if c["kind"] == "BPR"]
    if problems:
        print("STATUS PARSE PROBLEMS:")
        for p in problems:
            print(" ", p)
        sys.exit(1)
    if len(cr) != 38 or len(bpr) != 25:
        print(f"COUNT MISMATCH: CR={len(cr)} (want 38), BPR={len(bpr)} (want 25)")
        sys.exit(1)

    def y(v):
        v = str(v).replace('"', "'")
        return f'"{v}"'

    out = [
        "# AEGIS Control Set — Case_02 (SecureBorder Solutions) — GENERATED FILE",
        "# Source of truth: Doc18_Rules_Catalog.md §4/§5/§9 (DO NOT EDIT this file by hand).",
        "# Regenerate: python3 validation/build_control_set.py",
        "# Port Fase 5, 2026-08-28. Statuses are the deterministic legacy backfill per",
        "# IMPLEMENTATION_POSTURE_MODEL_CSF_STRICT.md §4 (the Case_01 '**' parsing bug is fixed here).",
        "control_set:",
        "  case: Case_02_SecureBorder_Solutions",
        "  version: 6.0",
        "  total_controls: 63",
        "  obligation_must: 38",
        "  best_practice_should: 25",
        "  controls:",
    ]
    for c in controls:
        out.append(f"    - id: {y(c['id'])}")
        out.append(f"      kind: {y(c['kind'])}")
        out.append(f"      type: {y('CONTROL — OBLIGATION (MUST)' if c['kind'] == 'CR' else 'BEST-PRACTICE (SHOULD)')}")
        out.append(f"      description: {y(c['description'])}")
        out.append(f"      source: {y(c['sources'])}")
        out.append(f"      sub_domain: {y(c['sub_domain'])}")
        out.append(f"      ni: {y(c.get('ni', c.get('type_line', '')))}")
        out.append(f"      priority: {y(c['priority'])}")
        out.append(f"      verification: {y(c['verification'])}")
        out.append(f"      related_goals: {y(c.get('related_goals', c.get('related_crs', '')))}")
        out.append(f"      csf: {y(c['csf'])}")
        out.append(f"      pf: {y(c['pf'])}")
        out.append(f"      airmf: {y(c['airmf'])}")
        out.append(f"      status_csf: {y(c['status_csf'])}")
        out.append(f"      status_privacy: {y(c['status_privacy'])}")
        out.append(f"      status_airmf: {y(c['status_airmf'])}")
        out.append(f"      traceability: {y(c['traceability'])}")
        out.append(f"      frameworks_ref: {y(c['frameworks_ref'])}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    dist_csf = {}
    for c in controls:
        dist_csf[c["status_csf"]] = dist_csf.get(c["status_csf"], 0) + 1
    print(f"control_set.yaml written: {len(controls)} controls (38 CR + 25 BPR)")
    print("status_csf distribution:", dist_csf)
    print("GATE-PASS condition: exit 0")


if __name__ == "__main__":
    main()
